In [2]:
import pandas as pd
import numpy as np
import itertools
import matplotlib.pyplot as plt

In [3]:
np.random.seed(1234)

real_male = np.random.randint(500, 660, size=6)
erro_male = np.random.uniform(0.7,1.2, size=6)
pred_male = np.round(real_male * erro_male)


real_female = np.random.randint(700, 800, size=6)
erro_female = np.random.uniform(0.85,1.25, size=6)
pred_female = np.round(real_female * erro_female)


real_nb = np.random.randint(60, 100, size=6)
erro_nb = np.random.uniform(0.2, 1.8, size=6)
pred_nb = np.round(real_nb * erro_nb)


months = np.arange(1, 7)

erro_male, erro_female, erro_nb



(array([1.13033489, 0.77531848, 0.79925938, 1.10758147, 0.77940768,
        0.75806891]),
 array([1.05123327, 0.85550738, 1.15913065, 1.20305648, 0.99595439,
        1.09615847]),
 array([1.24220503, 0.83552412, 1.46196823, 0.7069378 , 1.10895784,
        1.59060382]))

In [5]:
import plotly.graph_objects as go

# Dados de exemplo
# real = [10, 20, 30, 40, 50, 60, 70]   # Valores reais
# previsto = [12, 19, 32, 42, 48, 63, 68]  # Valores previstos

# Calculando o erro percentual
erro_percentual_male = [(p - r) / r  for p, r in zip(pred_male, real_male)]
erro_percentual_female = [(p - r) / r  for p, r in zip(pred_female, real_female)]
erro_percentual_nb = [(p - r) / r  for p, r in zip(pred_nb, real_nb)]
# print(erro_percentual)

# Criando o gráfico
fig = go.Figure()

# Adicionando a linha dos valores reais (linha base no eixo Y = 0)
fig.add_trace(go.Scatter(x=months, y=[0]*len(real_male), mode='lines', name='Real', line=dict(color='gray')))

# Adicionando a linha do erro percentual (valores previstos - reais)
fig.add_trace(go.Scatter(x=months, y=erro_percentual_female, mode='lines+markers', name='Erro Percentual - Gênero Feminino', line=dict(color='green', dash='dash')))
fig.add_trace(go.Scatter(x=months, y=erro_percentual_male, mode='lines+markers', name='Erro Percentual - Gênero Masculino', line=dict(color='red', dash='dash')))
fig.add_trace(go.Scatter(x=months, y=erro_percentual_nb, mode='lines+markers', name='Erro Percentual - Gênero Nao Binário', line=dict(color='blue', dash='dash')))

# Adicionando título e rótulos dos eixos
fig.update_layout(
    title='Predição do alcance de usuários',
    xaxis_title='Meses',
    yaxis_title='Erro Percentual',
    showlegend=True,
    xaxis=dict(
        tickvals=months,  # Define as posições dos ticks (valores reais)
        ticktext=["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho"],  # Rótulos dos meses
        # tickfont=dict(size=20)  # Tamanho da fonte dos ticks
    ),
    yaxis=dict(
        tickformat=".1%",  # Formato de porcentagem com 2 casas decimais
        tickfont=dict(size=14)  # Tamanho da fonte dos ticks do eixo Y
    )
)

# Exibindo o gráfico
fig.show()
